site_name: FastAPI Auth Middleware
site_description: "Python Package: FastAPI Auth Middleware"
site_author: Jonas Scholl, Yannic Schr√∂er
repo_url: https://github.com/code-specialist/fastapi-auth-middleware
repo_name: fastapi-auth-middleware

theme:
  name: material
  locale: en
  highlightjs: true
  favicon: ./img/favicon.svg
  logo: ./img/logo.png
  hljs_languages:
    - yaml
    - python
    - bash
    - shell
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Nunito Sans
    code: IBM Plex Mono
  features:
    - navigation.sections

nav:
  - Introduction: ./index.md
  - Examples:
    - Basic: ./examples/index.md
    - Basic with Scopes: ./examples/simple_with_scopes.md
    - Protected and Unprotected endpoints: ./examples/multiple.md
  - API Reference:
    - Middleware: ./api-reference/auth-middleware.md
    - Backend: ./api-reference/auth-backend.md
    - User: ./api-reference/user.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink:
  - admonition
  - attr_list
  - def_list
  - abbr
  - pymdownx.snippets

plugins:
- search
- mkdocstrings

extra_css:
  - ./css/styles.css

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/specialist_code/
      name: Code Specialist on Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCjdmChf65sGfOqWoygzBTyQ
      name: Code Specialist on YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/code-specialist
      name: Code Specialist on GitHub

copyright: Copyright &copy; 2021 Code Specialist | <a href="https://code-specialist.com/legal-notice/">Legal Notice</a>